#!/bin/sh
#
# Before running this shell script, be sure to have installed
# - jdk 8 and jre 8
# - all app dependencies
#

# install selenium-server-standalone-3
curl -O http://selenium-release.storage.googleapis.com/3.0/selenium-server-standalone-3.0.1.jar

# install chromedriver
curl -O http://chromedriver.storage.googleapis.com/2.27/chromedriver_mac64.zip
unzip chromedriver_mac64.zip
rm chromedriver_mac64.zip
